CREATE OR REPLACE VIEW PUBLIC.V_EXPERTISE_DISTINCT_COURT AS
SELECT DISTINCT
    T_COURT.C_ID,
    T_COURT.C_CODE,
    T_COURT.C_NAME
FROM PUBLIC.T_EXPERTISE
INNER JOIN PUBLIC.T_COURT
    ON T_EXPERTISE.C_COURT_ID = T_COURT.C_ID;
