CREATE OR REPLACE VIEW PUBLIC.V_EXPERTISE_SEARCH AS
SELECT
    T_EXPERTISE.C_ID,
    T_EXPERTISE.C_NUMBER,
    T_EXPERTISE.C_YEAR,
    T_EXPERTISE.C_NEXT_HEARING,
    T_EXPERTISE.C_TITLE,
    T_EXPERTISE.C_USER_ID AS C_RESPONSIBLE,
    T_COURT.C_NAME AS C_COURT,
    T_EXPERTISE.C_STATUS,
    UPPER(CONCAT_WS(' ', T_EXPERTISE.C_NUMBER, T_EXPERTISE.C_TITLE, T_COURT.C_NAME)) AS C_SEARCH
FROM PUBLIC.T_EXPERTISE
LEFT OUTER JOIN PUBLIC.T_COURT
    ON T_EXPERTISE.C_COURT_ID = T_COURT.C_ID
WHERE T_EXPERTISE.C_DELETED = 0;
