CREATE OR REPLACE VIEW PUBLIC.V_DELETED AS
(SELECT
    0 AS C_TYPE,
    T_PERSON.C_PERSON_TYPE AS C_SUBTYPE,
    T_PERSON.C_ID AS C_ID,
    CASE WHEN (T_PERSON.C_PERSON_TYPE = 0) THEN ((T_PERSON.C_FIRST_NAME || ' ') || T_PERSON.C_LAST_NAME) ELSE T_PERSON.C_NAME END AS C_TITLE,
    T_PERSON.C_CHANGEDON AS C_DELETEDON,
    UPPER(CONCAT_WS(' ', T_PERSON.C_FIRST_NAME, T_PERSON.C_LAST_NAME, T_PERSON.C_NAME)) AS C_SEARCH
FROM PUBLIC.T_PERSON
WHERE T_PERSON.C_DELETED = 1)
UNION ALL
(SELECT
    1 AS C_TYPE,
    0 AS C_SUBTYPE,
    T_EXPERTISE.C_ID AS C_ID,
    T_EXPERTISE.C_NUMBER AS C_TITLE,
    T_EXPERTISE.C_CHANGEDON AS C_DELETEDON,
    UPPER(CONCAT_WS(' ', T_EXPERTISE.C_NUMBER, T_EXPERTISE.C_TITLE)) AS C_SEARCH
FROM PUBLIC.T_EXPERTISE
WHERE T_EXPERTISE.C_DELETED = 1);
