CREATE OR REPLACE VIEW PUBLIC.V_GLOBAL_SEARCH AS 
(((SELECT 
    0 AS C_TYPE, 
    T_PERSON.C_PERSON_TYPE AS C_SUBTYPE, 
    T_PERSON.C_ID AS C_ID, 
    CASE WHEN (T_PERSON.C_PERSON_TYPE = 0) THEN ((T_PERSON.C_FIRST_NAME || ' ') || T_PERSON.C_LAST_NAME) ELSE T_PERSON.C_NAME END AS C_TITLE, 
    CONCAT_WS(', ', T_LOCATION_COUNTRY.C_NAME, T_LOCATION_REGION.C_NAME, T_LOCATION.C_ADDRESS) AS C_DESCRIPTION, 
    UPPER(CONCAT_WS(' ', T_PERSON.C_FIRST_NAME, T_PERSON.C_LAST_NAME, T_PERSON.C_NAME)) AS C_SEARCH 
FROM PUBLIC.T_PERSON 
LEFT OUTER JOIN PUBLIC.T_LOCATION 
    ON T_PERSON.C_LOCATION_ID = T_LOCATION.C_ID 
LEFT OUTER JOIN PUBLIC.T_LOCATION_COUNTRY 
    ON T_LOCATION.C_COUNTRY_ID = T_LOCATION_COUNTRY.C_ID 
LEFT OUTER JOIN PUBLIC.T_LOCATION_REGION 
    ON T_LOCATION.C_REGION_ID = T_LOCATION_REGION.C_ID 
WHERE T_PERSON.C_DELETED = 0) 
UNION ALL 
(SELECT 
    0 AS C_TYPE, 
    -1 AS C_SUBTYPE, 
    T_PERSON.C_ID AS C_ID, 
    T_PERSON_TELEPHONE.C_TELEPHONE AS C_NAME, 
    CASE WHEN (T_PERSON.C_PERSON_TYPE = 0) THEN ((T_PERSON.C_FIRST_NAME || ' ') || T_PERSON.C_LAST_NAME) ELSE T_PERSON.C_NAME END AS C_DESCRIPTION, 
    UPPER(T_PERSON_TELEPHONE.C_TELEPHONE) AS C_SEARCH 
FROM PUBLIC.T_PERSON 
INNER JOIN PUBLIC.T_PERSON_TELEPHONE 
    ON 1=1 
WHERE (T_PERSON.C_DELETED = 0) 
    AND (T_PERSON.C_ID = T_PERSON_TELEPHONE.C_PERSON_ID))) 
UNION ALL 
(SELECT 
    0 AS C_TYPE, 
    -2 AS C_SUBTYPE, 
    T_PERSON.C_ID AS C_ID, 
    T_PERSON_EMAIL_ADDRESS.C_EMAIL AS C_NAME, 
    CASE WHEN (T_PERSON.C_PERSON_TYPE = 0) THEN ((T_PERSON.C_FIRST_NAME || ' ') || T_PERSON.C_LAST_NAME) ELSE T_PERSON.C_NAME END AS C_DESCRIPTION, 
    UPPER(T_PERSON_EMAIL_ADDRESS.C_EMAIL) AS C_SEARCH 
FROM PUBLIC.T_PERSON 
INNER JOIN PUBLIC.T_PERSON_EMAIL_ADDRESS 
    ON 1=1 
WHERE (T_PERSON.C_DELETED = 0) 
    AND (T_PERSON.C_ID = T_PERSON_EMAIL_ADDRESS.C_PERSON_ID))) 
UNION ALL 
(SELECT 
    1 AS C_TYPE, 
    0 AS C_SUBTYPE, 
    C_ID, 
    C_NUMBER AS C_NAME, 
    C_TITLE AS C_DESCRIPTION, 
    UPPER(CONCAT_WS(' ', C_NUMBER, C_TITLE)) AS C_SEARCH 
FROM PUBLIC.T_EXPERTISE 
WHERE C_DELETED = 0);