CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_EXPERTISE( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_CHANGEDON TIMESTAMP, 
    C_CREATEDON TIMESTAMP, 
    C_DELETED BOOLEAN NOT NULL, 
    C_LAST_CHECKED_ON TIMESTAMP, 
    C_NOTE VARCHAR(512), 
    C_NUMBER VARCHAR(32), 
    C_STATUS INTEGER, 
    C_TITLE VARCHAR(128), 
    C_YEAR INTEGER, 
    C_ADVANCE NUMERIC(16, 2), 
    C_PRICE NUMERIC(16, 2), 
    C_NEXT_HEARING DATE, 
    C_CHANGEDBY_ID INTEGER, 
    C_CREATEDBY_ID INTEGER, 
    C_COURT_ID INTEGER NOT NULL, 
    C_USER_ID INTEGER, 
    C_LOCATION_ID INTEGER 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_LOCATION_ADM_UNIT( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_CODE VARCHAR(16), 
    C_NAME VARCHAR(128), 
    C_REGION_ID INTEGER NOT NULL
);


CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_LOCATION_COUNTRY( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_CODE VARCHAR(16), 
    C_NAME VARCHAR(128) 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_LOCATION_REGION( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_CODE VARCHAR(16), 
    C_NAME VARCHAR(128), 
    C_COUNTRY_ID INTEGER NOT NULL 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_PERSON( 
    C_PERSON_TYPE INTEGER NOT NULL, 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_CHANGEDON TIMESTAMP, 
    C_CREATEDON TIMESTAMP, 
    C_DELETED BOOLEAN DEFAULT FALSE, 
    C_ID_NUMBER VARCHAR(64), 
    C_JOINT_STOCK DECIMAL(16, 2), 
    C_NAME VARCHAR(128), 
    C_REG_NUMBER VARCHAR(64), 
    C_FIRST_NAME VARCHAR(128), 
    C_ID_CARD_NUMBER VARCHAR(32), 
    C_ID_CARD_TYPE INTEGER, 
    C_LAST_NAME VARCHAR(128), 
    C_PERSONAL_NUMBER VARCHAR(32), 
    C_CHANGEDBY_ID INTEGER, 
    C_CREATEDBY_ID INTEGER, 
    C_LOCATION_ID INTEGER NOT NULL
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_PERSON_BANK_ACCOUNT( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_ACCOUNT_NUMBER VARCHAR(64), 
    C_BANK VARCHAR(128), 
    C_PRIMARY BOOLEAN, 
    C_PERSON_ID INTEGER NOT NULL 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_PERSON_EMAIL_ADDRESS( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_EMAIL VARCHAR(128), 
    C_NAME VARCHAR(64), 
    C_PRIMARY BOOLEAN, 
    C_PERSON_ID INTEGER NOT NULL
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_PERSON_TELEPHONE( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_NAME VARCHAR(64), 
    C_PRIMARY BOOLEAN, 
    C_TELEPHONE VARCHAR(128), 
    C_PERSON_ID INTEGER NOT NULL 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_USER_FAVOURITE( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_HASH VARCHAR(64), 
    C_TITLE VARCHAR(64), 
    C_USER_ID INTEGER NOT NULL 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_USER_HOME_TILE( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_NAME VARCHAR(32), 
    C_ORDER INTEGER, 
    C_VISIBLE BOOLEAN, 
    C_USER_ID INTEGER NOT NULL 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_USER( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_ACTIVE BOOLEAN, 
    C_PASSWORD VARCHAR(1024), 
    C_SALT VARCHAR(64), 
    C_USERNAME VARCHAR(30), 
    C_FAILS INTEGER 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_COURT( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_CODE VARCHAR(16), 
    C_NAME VARCHAR(128) 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_USER_SESSION( 
    C_ID VARCHAR(128) PRIMARY KEY, 
    C_ACCESS_TIME BIGINT, 
    C_ATTRIBUTES BLOB, 
    C_CONTEXT_PATH VARCHAR(64), 
    C_COOKIE_TIME BIGINT, 
    C_CREATE_TIME BIGINT, 
    C_EXPIRY_TIME BIGINT, 
    C_LAST_ACCESS_TIME BIGINT, 
    C_LAST_NODE VARCHAR(64), 
    C_LAST_SAVE_TIME BIGINT, 
    C_MAX_INTERVAL BIGINT, 
    C_VIRTUAL_HOST VARCHAR(64) 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_USER_PREFERENCE( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_DRAFT_RESUME_DELAY INTEGER, 
    C_LANGUAGE VARCHAR(16), 
    C_THEME VARCHAR(32), 
    C_USER_ID INTEGER NOT NULL 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_EXPERTISE_FINE( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_DATE DATE, 
    C_SUM NUMERIC(16, 2), 
    C_EXPERTISE_ID INTEGER 
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_LOCATION( 
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
    C_ADDRESS VARCHAR(512), 
    C_GEOCODED BOOLEAN DEFAULT FALSE, 
    C_LATITUDE DOUBLE, 
    C_LONGITUDE DOUBLE, 
    C_ADM_UNIT_ID INTEGER, 
    C_COUNTRY_ID INTEGER, 
    C_REGION_ID INTEGER
);