ALTER TABLE PUBLIC.T_USER_PREFERENCE DROP CONSTRAINT IF EXISTS PUBLIC.FKMMODM3SCEAISNQUY0QHICYQK4;
ALTER TABLE PUBLIC.T_USER_PREFERENCE DROP COLUMN IF EXISTS C_USER_ID;

ALTER TABLE PUBLIC.T_USER ADD COLUMN IF NOT EXISTS C_PREFERENCE_ID INTEGER NOT NULL;
ALTER TABLE PUBLIC.T_USER ADD CONSTRAINT IF NOT EXISTS PUBLIC.T_USER_C_PREFERENCE_ID
    FOREIGN KEY(C_PREFERENCE_ID)
    REFERENCES PUBLIC.T_USER_PREFERENCE(C_ID) ON DELETE CASCADE NOCHECK;
