ALTER TABLE PUBLIC.T_USER_FAVOURITE ALTER COLUMN C_USER_ID SET NULL;
ALTER TABLE PUBLIC.T_USER_HOME_TILE ALTER COLUMN C_USER_ID SET NULL;

ALTER TABLE PUBLIC.T_PERSON ALTER COLUMN C_LOCATION_ID SET NULL;
ALTER TABLE PUBLIC.T_PERSON_BANK_ACCOUNT ALTER COLUMN C_PERSON_ID SET NULL;
ALTER TABLE PUBLIC.T_PERSON_TELEPHONE ALTER COLUMN C_PERSON_ID SET NULL;
ALTER TABLE PUBLIC.T_PERSON_EMAIL_ADDRESS ALTER COLUMN C_PERSON_ID SET NULL;

ALTER TABLE PUBLIC.T_EXPERTISE_FINE ALTER COLUMN C_EXPERTISE_ID SET NULL;
ALTER TABLE PUBLIC.T_EXPERTISE ALTER COLUMN C_LOCATION_ID SET NULL;
ALTER TABLE PUBLIC.T_EXPERTISE ALTER COLUMN C_COURT_ID SET NULL;
